spring.application.name=hospitalManagementSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalManagement_db
spring.datasource.username=postgres
spring.datasource.password=2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.security.user.name=ravi
#spring.security.user.password=1234
Jwt.Secretkey=${JwtSecretKey}
spring.security.oauth2.client.registration.google.client-id=${Google_Client_ID}
spring.security.oauth2.client.registration.google.client-secret=${Google_Client_Secret}